### ISSUE TITLE
README.md checklist

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/agile-development-group2-all-about-trees#5]
# README.md
Checklist that we must have in our group README

## Checklist

- [x] Project name
- [x] Brief description
- [ ] Code of conduct or community guidelines
- [ ] Contact information for the project maintainer or team
- [ ] Screenshot/Picture
- [ ] Tools we use
- [ ] Known issues and troubleshooting tips
- [ ] Code examples
- [x] Project status
- [x] Acknowledgments or credits for external resources or contributors
- [x] Contributing guidelines and instructions
- [ ] License information
